{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"name":"10_excepction_management_con_respuestas.ipynb","version":"0.3.2","provenance":[]}},"cells":[{"metadata":{"id":"Oj0teCJiQYdm","colab_type":"code","colab":{}},"cell_type":"code","source":["SANDBOX_NAME = # Sandbox Name\n","DATA_PATH = \"/data/sandboxes/\"+SANDBOX_NAME+\"/data/\""],"execution_count":0,"outputs":[]},{"metadata":{"id":"57enxUegQYds","colab_type":"text"},"cell_type":"markdown","source":["\n","\n","# Control de Excepciones"]},{"metadata":{"id":"GBsvYKxwQYdt","colab_type":"text"},"cell_type":"markdown","source":["\n","\n","A lo largo de la ejecución de programas en python pueden suceder multitud de errores, conocidos como excepciones. Estas excepciones hacen que el programa termine abruptamente si no son debidamente tratadas.\n","\n","Surgen a partir de caminos en la ejecución que no se han tenido en cuenta o se programan para declarar una circunstancia que impide un a ejecución normal.\n","\n","Tras descubrir una excepción, habría que modificar el código para que dada esa circunstancia específica la ejecución no se detenga de manera incontrolada.\n","\n","Por lo anterior, se habla de control de excepciones."]},{"metadata":{"id":"pSQaO-1OQYdu","colab_type":"text"},"cell_type":"markdown","source":["\n","\n","# Tipos de excepciones"]},{"metadata":{"id":"wtVh7ajvQYdv","colab_type":"text"},"cell_type":"markdown","source":["\n","\n","Las excepciones más comunes en python son:\n","- **ImportError** Python no puede encontar el módulo\n","- **TypeError** Tipo de dato inadecuado para esta operación\n","- **ValueError** Tipo de dato adecuado para la operación, pero de valor incorrecto\n","    (Recibe un objeto, pero no de la clase esperada)\n","- **KeyboardInterrupt** Se interrumpe la ejecución mediante el teclado (Control-C)\n"]},{"metadata":{"id":"G9Ii2n54QYdw","colab_type":"code","colab":{}},"cell_type":"code","source":["a = (1,2,3)\n","(x,y) = a"],"execution_count":0,"outputs":[]},{"metadata":{"id":"Cti8s93ZQYdz","colab_type":"code","colab":{}},"cell_type":"code","source":["class MyClass():\n","    pass\n","len(MyClass())"],"execution_count":0,"outputs":[]},{"metadata":{"id":"OJjGZ4eWQYd2","colab_type":"text"},"cell_type":"markdown","source":["\n","\n","# Lanzando excepciones"]},{"metadata":{"id":"qTWEfeYzQYd3","colab_type":"text"},"cell_type":"markdown","source":["\n","\n","Se pueden lanzar excepciones programáticamente con"]},{"metadata":{"id":"-Aa9VZ4tQYd4","colab_type":"code","colab":{}},"cell_type":"code","source":["raise TypeError(\"A list is required for this operation\")"],"execution_count":0,"outputs":[]},{"metadata":{"id":"poKIZNKsQYd6","colab_type":"code","colab":{}},"cell_type":"code","source":["raise ValueError(\"This value is not valid\")"],"execution_count":0,"outputs":[]},{"metadata":{"id":"nIIyYHK5QYd9","colab_type":"text"},"cell_type":"markdown","source":["\n","\n","por ejemplo en una función"]},{"metadata":{"id":"86LAZsydQYd-","colab_type":"code","colab":{}},"cell_type":"code","source":["def division(a, b):\n","    if not isinstance(a,(int,float)):\n","        raise TypeError(\"'a' must be a number\")\n","    \n","    if not isinstance(b,(int,float)):\n","        raise TypeError(\"'b' must be a number\")    \n","    \n","    return a / b"],"execution_count":0,"outputs":[]},{"metadata":{"id":"S4-3A0EyQYeA","colab_type":"code","colab":{}},"cell_type":"code","source":["division(1,1)"],"execution_count":0,"outputs":[]},{"metadata":{"id":"gsF-A4OtQYeD","colab_type":"code","colab":{}},"cell_type":"code","source":["division(\"uno\",1)\n","print(\"this is run, therefore our program continues\")"],"execution_count":0,"outputs":[]},{"metadata":{"id":"maYq03UEQYeG","colab_type":"code","colab":{}},"cell_type":"code","source":["try:\n","    division(1,0)\n","except TypeError as e:\n","    print(e)\n","#except ZeroDivisionError as e:\n","#    print(e)\n","\n","print(\"this is run, therefore our program continues\")"],"execution_count":0,"outputs":[]},{"metadata":{"id":"dFNMTKJYQYeJ","colab_type":"code","colab":{}},"cell_type":"code","source":["def my_age(age):\n","    if not isinstance(age,int):\n","        raise TypeError(\"ERROR: Age must be an integer\")\n","\n","    if(age > 100 or age < 0):\n","        raise ValueError(\"ERROR: Age out of range (0, 100)\")\n","    print(\"The age is: \", age)"],"execution_count":0,"outputs":[]},{"metadata":{"id":"J1Ux9Gu5QYeL","colab_type":"code","colab":{}},"cell_type":"code","source":["my_age(10)"],"execution_count":0,"outputs":[]},{"metadata":{"id":"gWbq7ZQjQYeO","colab_type":"code","colab":{}},"cell_type":"code","source":["my_age(-1)"],"execution_count":0,"outputs":[]},{"metadata":{"id":"hF_6HLw0QYeQ","colab_type":"code","colab":{}},"cell_type":"code","source":["my_age(\"hello\")"],"execution_count":0,"outputs":[]},{"metadata":{"id":"fUuUa519QYeS","colab_type":"text"},"cell_type":"markdown","source":["\n","\n","# Controlando excepciones. `try` `except`"]},{"metadata":{"id":"CycHvT5WQYeT","colab_type":"text"},"cell_type":"markdown","source":["\n","\n","Se puede \"intentar\" realizar cualquier ejecución que sea susceptible de lanzar una excepción, y en caso de que se produzca una excepción, recogerla, y continuar con el resto del programa."]},{"metadata":{"id":"jXOU4YxtQYeU","colab_type":"code","colab":{}},"cell_type":"code","source":["try:\n","    division(\"a\",1)\n","except TypeError as e:\n","    print(e)\n","print(\"this is run, therefore our program continues\")"],"execution_count":0,"outputs":[]},{"metadata":{"id":"ikxrj2toQYeZ","colab_type":"text"},"cell_type":"markdown","source":["\n","\n","Se pueden apilar las excepts, para diferentes tipos de excepciones"]},{"metadata":{"id":"Z1ECvKMDQYea","colab_type":"text"},"cell_type":"markdown","source":["\n","\n","En ciertas ocasiones NO sabemos que puede llegar a ocurrir detrás de una llamada. Utilizamos la función random del paquete random para hacer esta prueba."]},{"metadata":{"id":"XeyoPLxVQYeb","colab_type":"code","colab":{}},"cell_type":"code","source":["import random\n","random.randrange?"],"execution_count":0,"outputs":[]},{"metadata":{"id":"9ixB8CrPQYeg","colab_type":"code","colab":{}},"cell_type":"code","source":["class MyClass():\n","    pass\n","\n","options = [\"texto\", 1, 0, 0.5, MyClass(), [], {}]\n","options[random.randrange(0,len(options))]"],"execution_count":0,"outputs":[]},{"metadata":{"id":"fRC9tZIKQYej","colab_type":"code","colab":{}},"cell_type":"code","source":["def random_object():\n","    return options[random.randrange(0,len(options))]"],"execution_count":0,"outputs":[]},{"metadata":{"id":"MU2x4SrBQYen","colab_type":"code","colab":{}},"cell_type":"code","source":["a = random_object()\n","b = random_object()\n","\n","try:\n","    print(a + b)\n","except TypeError as e:\n","    print(e)\n","\n","try:\n","    print(str(a) + str(b))\n","except TypeError as e:\n","    print(e)\n"],"execution_count":0,"outputs":[]},{"metadata":{"id":"oMhgpjbKQYeq","colab_type":"code","colab":{}},"cell_type":"code","source":["try:\n","    my_age(-1)\n","except TypeError as e:\n","    print(e)\n","except ValueError as e:\n","    print(e)\n","    print(\"We force default load\")\n","    my_age(30)\n","print(\"Program reaches this point\")"],"execution_count":0,"outputs":[]},{"metadata":{"id":"7w4UOHjEQYet","colab_type":"text"},"cell_type":"markdown","source":["\n","\n","## Ejercicios"]},{"metadata":{"id":"bf-P7uH4QYeu","colab_type":"text"},"cell_type":"markdown","source":["\n","\n","### Ejercicio 1"]},{"metadata":{"id":"yxvtpu5kQYev","colab_type":"text"},"cell_type":"markdown","source":["\n","\n","Escriba código para que realice lo siguiente:\n","1. Solicite por pantalla un número\n","2. Solicite por pantalla otro número\n","3. Imprima a/b = resultado división\n","4. Imprima a+b = resultado suma\n","Todo ello, con control de excepciones, imprimiendo las causas de los diferentes tipos de errores.\n","\n","Por ejemplo, si se introduce: \"hola\", y luego 3, debería imprimir que no se convertir a número. O si se introduce primero 3 y luego 0, debería imprimir que no se puede dividir por 0. \n","\n","Nota: controlar también algún otro tipo de error inesperado. Y en este caso, lanzar una excepción para que se interrumpa el programa."]},{"metadata":{"id":"t9fsyCGiQYew","colab_type":"code","colab":{}},"cell_type":"code","source":["# Respuesta\n","\n","try:\n","    a = int(input(\"Enter a number: \"))\n","    b = int(input(\"Enter a number: \"))\n","    print(\"a/b = \", a/b)\n","    print(\"a+b = \", a+b)\n","except ValueError:\n","    print(\"Cannot be casted into a number.\")\n","except ZeroDivisionError:\n","    print(\"Division by 0 is not allowed\")\n","except:\n","    print(\"There was an error.\")\n","\n","\n"],"execution_count":0,"outputs":[]},{"metadata":{"id":"Oc2tOGJ0QYey","colab_type":"text"},"cell_type":"markdown","source":["\n","\n","### Ejercicio 2 "]},{"metadata":{"id":"h2jACnscQYez","colab_type":"text"},"cell_type":"markdown","source":["\n","\n","Define una función que, dadas dos listas de igual longitud, devuelva una lista final conteniendo **L1[i]/L2[i].**\n","\n","\n","Tenga en cuenta los errores que puedan surgir, y contrólelos.\n","- En el caso que sea una división por cero, inserte en la lista final nan (not a number) en la posición de dicha división de elementos.\n","- En el caso que la excepción sea causada por un mal argumento, lance una excepción que interrumpa el programa.\n","- En el caso que no haya problema y se pueda insertar en la posición i de la lista final el elemento tras la división, imprima que ha sido un éxito por pantalla."]},{"metadata":{"id":"d6j_PYilQYe0","colab_type":"code","colab":{}},"cell_type":"code","source":["# Respuesta\n","\n","def get_ratios(L1, L2):\n","    \"\"\" Assumes that L1 and L2 are lists of equal length\n","        Returns: a list of content L1[i]/L2[i] \"\"\"\n","    ratios = []\n","    for index in range(len(L1)):\n","        try:\n","            ratios.append(L1[index]/L2[index])\n","        except ZeroDivisionError:\n","            ratios.append(float('nan')) #float('nan') resulta en NaN (not a number)\n","        except:\n","            raise ValueError('get_ratios was called with the wrong argument')\n","        else:\n","            print(\"Success!\")\n","        finally:\n","            print(\"This part runs no matter what!\")\n","    return ratios\n","\n","l = get_ratios([1, 0], [2, 0])\n","print(l)"],"execution_count":0,"outputs":[]},{"metadata":{"id":"IbAb05NXQYe3","colab_type":"text"},"cell_type":"markdown","source":["\n","\n","### Ejercicio 3"]},{"metadata":{"id":"hvpbUmJ9QYe3","colab_type":"text"},"cell_type":"markdown","source":["\n","\n","Escribe código que:\n","    - Pida por pantalla el nombre de un fichero\n","    - Intente abrirlo para lectura\n","    - Si no lo encuentra, imprima por pantalla que no existe, y que vuelva a intentarlo el usuario\n","    - Realizar esto hasta que se encuentre un fichero con dicho nombre"]},{"metadata":{"id":"XYLkM3IyQYe4","colab_type":"code","colab":{}},"cell_type":"code","source":["# Respuesta\n","\n","while True:\n","    try:\n","        filename = input(\"Enter filename: \").strip()\n","        infile = open(filename, \"r\") # Open the file\n","        break \n","    except IOError:\n","        print(\"The file \" + filename + \" does not exist. Try again!\")"],"execution_count":0,"outputs":[]},{"metadata":{"id":"_9ybZtxsQYe7","colab_type":"text"},"cell_type":"markdown","source":["\n","\n","## Ejercicio 3"]},{"metadata":{"id":"LA5dxIqEQYe8","colab_type":"text"},"cell_type":"markdown","source":["\n","\n","Escriba código tal que:\n","    - Solicite dos enteros por pantalla\n","    - Realice la división y la imprima\n","    - Con control de errores, imprima un mensaje si la división es por 0, si hay otro error en el input, \n","    y si no hay excepciones que salten, pero que no se interrumpa la ejecución del programa.\n","    - Y que siempre, pase lo que pase, imprima una frase final (aunque hubiese interrupción en el programa)."]},{"metadata":{"id":"QKQEfDJiQYe9","colab_type":"code","colab":{}},"cell_type":"code","source":["# Respuesta\n","\n","def main():\n","    try:\n","        number1 = int(input(\"Enter an integer: \"))      \n","        number2 = int(input(\"Enter an integer: \"))      \n","        result = number1 / number2\n","        print(\"Results: \" + str(result))\n","    except ZeroDivisionError:\n","        print(\"Division by 0 not allowed!\")\n","    except:\n","        print(\"There is an error in the input\")\n","    else:\n","        print(\"No exceptions raised\")\n","    finally:\n","        print(\"Code in the finally block is always run\")\n","\n","main()"],"execution_count":0,"outputs":[]},{"metadata":{"id":"i3w2LISPQYe_","colab_type":"text"},"cell_type":"markdown","source":["\n","\n","### Ejercicio 4"]},{"metadata":{"id":"rqkpmOLoQYfA","colab_type":"text"},"cell_type":"markdown","source":["\n","\n","Escriba código de una función que reciba como argumento el nombre de un fichero, abra el fichero, y si no lo encuentra, imprima un error diciendo que no se ha encontrado, y devuelva false.\n","En caso que se encuentre, imprime por pantalla cada línea del fichero en mayúsculas, y devuelve true. "]},{"metadata":{"id":"ejItRsm6QYfA","colab_type":"code","colab":{}},"cell_type":"code","source":["# Respuesta\n","\n","def printUpperFile( fileName ):\n","    try:\n","        file = open( fileName, \"r\" )\n","    except FileNotFoundError:\n","        print( \"***Error*** The file\", fileName, \"was not found!\" )\n","        return False\n","    \n","    for line in file:\n","        print( line.upper() )\n","    file.close()\n","    return True"],"execution_count":0,"outputs":[]},{"metadata":{"id":"1v3GaBulQYfE","colab_type":"code","colab":{}},"cell_type":"code","source":["printUpperFile(\"files/file.txt\")"],"execution_count":0,"outputs":[]}]}